---
title: "MARSS Model to Iterpolate Missing Streamflow Observations"
author: "Thomas Buehrens"
date: "2022-11-05"
output:
  html_document:
    code_folding: hide
    fig_caption: yes
    theme: cerulean
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

## Setup
```{r setup, set_options, echo = TRUE, message = FALSE}
#==========================================
#function to install or load packages
#==========================================
install_or_load_pack <- function(pack){
  create.pkg <- pack[!(pack %in% installed.packages()[, "Package"])]
  if (length(create.pkg))
    install.packages(create.pkg, dependencies = TRUE)
  sapply(pack, require, character.only = TRUE)
}

#===============================
# function to get USGS flow data
#===============================
get_USGS_data<-function(flow_site,flow_params,daily_or_instantaneous,begin_date,end_date){
  flow_params_lookup<-tibble(flow_params=c("discharge","stage_height"),
                       param_codes=c("00060","00065"))%>%
    right_join(tibble("flow_params"=flow_params))%>%
    dplyr::select(param_codes)%>%
    as.vector()%>%
    unlist()
  
  names_lookup_daily<-c("Date" = "date","Flow" ="flow_cfs","GH" ="stage_height")
  names_lookup_inst<-c("Date" ="date","Flow_Inst"="flow_cfs","GH_Inst" ="stage_height" )                    
  
  if(daily_or_instantaneous=="daily"){
    tdat<- readNWISdv(siteNumber=flow_site,
                parameterCd = flow_params_lookup, 
                startDate = begin_date,
                endDate = end_date, 
                statCd = "00003")%>%
      renameNWISColumns()%>%
      as_tibble()%>%
      rename_with(.fn = ~names_lookup_daily[.x], .cols = intersect(names(.), names(names_lookup_daily)))
  }else{
    tdat <- readNWISuv(siteNumber = flow_site,
                       parameterCd = flow_params_lookup,
                       startDate =begin_date,
                       endDate = end_date)%>%
      renameNWISColumns()%>%
      as_tibble()%>%
      rename_with(.fn = ~names_lookup_inst[.x], .cols = intersect(names(.), names(names_lookup_inst)))
  }
  return(tdat)
}

#====================================
# function to get ecology flow data
#==================================
get_DOE_data<-function(begin_date,end_date,flow_site,flow_params,daily_or_instantaneous){

  begin_year = ifelse(month(begin_date) < 10, year(begin_date)-1,year(begin_date)) #by water year
  end_year = year(end_date)
  years<-c(begin_year:end_year)
  
  flow_params_lookup<-tibble(flow_params=c("discharge","stage_height"),
                       param_codes=c("DSG","STG"))%>%
    right_join(tibble("flow_params"=flow_params))%>%
    dplyr::select(param_codes)%>%
    as.vector()%>%
    unlist()
  
  daily_inst_lookup<-tibble(daily_or_instantaneous=c("daily","instantaneous"),
                       param_codes=c("DV","FM"))%>%
    right_join(tibble("daily_or_instantaneous"=daily_or_instantaneous))%>%
    dplyr::select(param_codes)%>%
    as.vector()%>%
    unlist()
  
  
  names_lookup<-c("DATE" = "date","TIME" = "time", "Discharge(cfs)" ="flow_cfs","Stage(ft.)" ="stage_height", "STAGE(ft.)" ="stage_height", `FLOW(cfs)` = "flow_cfs","QUALITY" = "quality")
  
  flow_dat<-NULL
  
  for(i in years){
    url<-paste0("https://apps.ecology.wa.gov/ContinuousFlowAndWQ/StationData/Prod/",flow_site,"/",flow_site,"_",i,"_",flow_params_lookup,"_",daily_inst_lookup,".TXT")
    try(
    if(i==min(years)){
      names<-grep("DATE",read_lines(url,skip_empty_rows = T),invert=F,value=T)%>%
        str_split("  ")%>%
        as_vector()
      names = names[names!=""]
      names<-as.vector(gsub("\\s", "", names))
      flow_dat<-grep("/20",read_lines(url,skip_empty_rows = T),invert=F,value=T)%>%
        read_table(na=" ",col_names = F)%>%
        set_names(names)%>%
        filter(QUALITY %in% c(1,2,3,10))%>%
        rename_with(.fn = ~names_lookup[.x], .cols = intersect(names(.), names(names_lookup)))%>%
        mutate(date = mdy(date))%>%
        mutate(across(any_of(c("stage_height","flow_cfs","quality")),~as.numeric(.)))
    }else{
      names<-grep("DATE",read_lines(url,skip_empty_rows = T),invert=F,value=T)%>%
        str_split("  ")%>%
        as_vector()
      names = names[names!=""]
      names<-as.vector(gsub("\\s", "", names))
      tdat<-grep("/20",read_lines(url,skip_empty_rows = T),invert=F,value=T)%>%
        read_table(na=" ",col_names = F)%>%
        set_names(names)%>%
        filter(QUALITY %in% c(1,2,3,10))%>%
        rename_with(.fn = ~names_lookup[.x], .cols = intersect(names(.), names(names_lookup)))%>%
        mutate(date = mdy(date))%>%
        mutate(across(any_of(c("stage_height","flow_cfs","quality")),~as.numeric(.)))
      if(is.null(flow_dat)){
        flow_dat<-tdat
      }else{
        flow_dat<-flow_dat%>%
          bind_rows(tdat)
      }
    }
    )
  }
  flow_dat<-flow_dat%>%
    filter(date>=ymd(begin_date) & date <= ymd(end_date))
  return(flow_dat)
}

packages_list<-c("MARSS",
                 "tidyverse",
                 "lubridate", 
                 "kableExtra",
                 "dataRetrieval"
                 ) #BTSPAS loads separately
install_or_load_pack(packages_list)
```

## Flow Data
Get Naselle and Grays flow data
```{r message = FALSE, warning = FALSE,results = "hide"}
naselle<-get_USGS_data(flow_site =12010000, #Naselle
                        flow_params ="discharge",
                        daily_or_instantaneous= "daily",
                        begin_date = "2002-10-01",
                        end_date = "2022-09-30"
                        )

grays<-get_DOE_data(flow_site ="25B060", #Grays
                        flow_params ="discharge",
                        daily_or_instantaneous= "daily",
                        begin_date = "2002-10-01",
                        end_date = "2022-09-30"
                        )

elochoman<-get_DOE_data(flow_site ="25C060", #Elochoman
                        flow_params ="discharge",
                        daily_or_instantaneous= "daily",
                        begin_date = "2002-10-01",
                        end_date = "2022-09-30"
                        )

abernathy<-get_DOE_data(flow_site ="25E060", #Abernathy
                        flow_params ="discharge",
                        daily_or_instantaneous= "daily",
                        begin_date = "2002-10-01",
                        end_date = "2022-09-30"
                        )

chehalis_doty<-get_USGS_data(flow_site ="12020000", #Chehalis_doty
                        flow_params ="discharge",
                        daily_or_instantaneous= "daily",
                        begin_date = "2002-10-01",
                        end_date = "2022-09-30"
                        )


flow_dat<-naselle%>%
  dplyr::select(date,flow_cfs)%>%
  mutate(river="naselle")%>%
  bind_rows(grays%>%
              dplyr::select(date,flow_cfs)%>%
              mutate(river="grays")
              )%>%
  bind_rows(elochoman%>%
              dplyr::select(date,flow_cfs)%>%
              mutate(river="elochoman")
              )%>%
  bind_rows(abernathy%>%
              dplyr::select(date,flow_cfs)%>%
              mutate(river="abernathy")
              )%>%
  bind_rows(chehalis_doty%>%
              dplyr::select(date,flow_cfs)%>%
              mutate(river="chehalis_doty")
              )%>%
  group_by(river,date)%>%
  summarise(flow_cfs=mean(flow_cfs),.groups = "keep")%>%
  ungroup()%>%
  group_by(river)%>%
  mutate(zl_flow_cfs=as.vector(scale(log(flow_cfs))))%>%
  ungroup()#%>%
  # mutate(flow_cfs=ifelse(river=="grays" & zl_flow_cfs <= -2,NA,flow_cfs),
  #        )%>%
  # filter(!is.na(flow_cfs))%>%
  # group_by(river)%>%
  # mutate(zl_flow_cfs=as.vector(scale(log(flow_cfs))))
  
  flow_dat%>%group_by(river)%>%summarize(min_zl_flow=min(zl_flow_cfs),
                                         min_flow=min(flow_cfs)
                                         )
  
```

## Plot Flow Data
```{r message = FALSE, warning = FALSE,results = "show", fig.show=TRUE,fig.cap="Figure 1. Observed z-scored logged flow by river."}
ggplot(flow_dat,aes(x=date,y = zl_flow_cfs,color=river),alpha=0.5)+
  geom_point(size=0.3)
```

## MARSS Model 
```{r  message = FALSE, warning = FALSE,results = "hide"}
marss_dat<-flow_dat%>%
  dplyr::select(river,date,zl_flow_cfs)%>%
  pivot_wider(names_from = river,values_from = zl_flow_cfs,id_cols=date)%>%
  arrange(date)%>%
  mutate(jdate=julian(date))%>%
  filter(year(date)>2020)

all_dates<-tibble(jdate=julian(min(marss_dat$date)):julian(max(marss_dat$date)))

marss_dat<-all_dates%>%
  left_join(marss_dat)

marss_mat<-marss_dat%>%
  dplyr::select(-c(date,jdate))%>%
  as.matrix()%>%
  t()


model=list(
 Q= "equalvarcov",#"unconstrained"
 R= "diagonal and equal",
 U= matrix(rep(0,5),5,1)
)
fit=MARSS(marss_mat, model=model)

fitted<-t(fit$states)
colnames(fitted)<-gsub("X.","mle_",colnames(fitted))

marss_dat<-marss_dat%>%
  dplyr::select(-jdate)%>%
  bind_cols(fitted)%>%
  pivot_longer(cols=c(everything(),-date),names_to = "river")%>%
  mutate(type=ifelse(grepl("mle_",river),"mle","obs"))%>%
  mutate(river=gsub("mle_","",river))%>%
  pivot_wider(values_from =value,names_from = type)%>%
  arrange(river,date)
#write.csv(marss_dat,"marss_dat.csv")
```

## Plot Flow Data with MARSS Predictions
```{r  message = FALSE, warning = FALSE,results = "show", fig.show=TRUE,fig.cap="Figure 2: Comparison of Observed z-scored logged flow vs. MARSS fits"}
ggplot(marss_dat,aes(x=date,y=mle,group=river))+
  geom_line(color="cadetblue")+
  geom_point(aes(y=obs),size=0.1)+
  facet_wrap(~river)
```
